controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
produits_details:
    path: /produits/{slug}
    controller: App\Controller\ProductsController::details